### ISSUE TITLE
Expose command history from the tree in Open MCT

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#172]
**Is your feature request related to a problem? Please describe.**
It's sometimes useful to see which commands have been recently executed, and in particular for this list to be updated in real-time.

**Describe the solution you'd like**
Yamcs provides [an API](https://docs.yamcs.org/yamcs-http-api/commands/list-commands/) for retrieving a list of commands executed recently, as well as a subscription mechanism. We could expose a new telemetry point from the tree called "Command History" which exposes command history, and real-time command execution like telemetry. This would allow it to be displayed in a telemetry table. 

A note on implementation, this should be implemented in the same way that the have implemented Events. That said, we currently have [a single object provider](https://github.com/akhenry/openmct-yamcs/blob/0d25ba199cf8dfcccd6a94a6747fe1d8b1cf3e49/src/providers/object-provider.js), [realtime telemetry provider](https://github.com/akhenry/openmct-yamcs/blob/0d25ba199cf8dfcccd6a94a6747fe1d8b1cf3e49/src/providers/realtime-provider.js), and [historical telemetry provider](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/historical-telemetry-provider.js) for both telemetry _and_ events, with internal logic to differentiate between the different cases (eg. [here](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/object-provider.js#L53), [here](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/historical-telemetry-provider.js#L200), and [here](https://github.com/akhenry/openmct-yamcs/blob/0d25ba199cf8dfcccd6a94a6747fe1d8b1cf3e49/src/providers/realtime-provider.js#L193)). Adding command history into the mix is likely to cause some spaghetification of our code, so as part of this we should look at how we might separate out the telemetry, Events, and Command History specific logic.

**Comment by charlesh88** [comment]
Absolutely yes, this has a lot of utility. I've added this to the User Request repo as https://trunk.arc.nasa.gov/jira/browse/VIPERRQSTS-213.

**Comment by ozyx** [comment]
# Testing Instructions

## Fixed time

1. Ensure there is an active YAMCS instance with some kind of command history
2. Navigate to Open MCT instance with openmct-yamcs plugin installed
3. In the tree pane, expand any yamcs project folder
4. Verify there is a static object present "Commands"
5. Focus the "Commands" object
6. Switch to fixed time mode. Expand the time bounds so that it includes YAMCS command history
7. Verify that a single telemetry row is displayed for each command sent within the time bounds, with each column populated
9. Right click, select "view full datum", verify that each key has a corresponding value

## Realtime

1. Navigate to the "Commands" static object
2. Switch to realtime mode
3. Send a command via yamcs interface
4. Verify that telemetry rows appear for each sequence of the command (this will be updated in a future PR to modify a single row)
5. Right click on a single telemetry row, click "View Full Datum"
6. Verify that each key has a corresponding value

**Comment by charlesh88** [comment]
Testathon 10-04-22 verified fixed.

**Comment by akhenry** [comment]
Verified Fixed
