### ISSUE TITLE
[Build] Update webpack config to match openmct

### ISSUE THREAD

**Issue by unlikelyzero** [akhenry/openmct-yamcs#196]
#### Summary
Open MCT has removed app.js and converted to a webpack-dev-server config. We should update this repo's implementation to match.

#### Current scope
- [ ] copy openmct's webpack.common.config or webpack.coverage.config
- [ ] Add proxy section
- [ ] Verify that proxy section works in CI and on local execution
- [ ] Update `npm start` to follow `openmct`'s script

**Comment by akhenry** [comment]
[It uses webpack dev server](https://github.com/akhenry/openmct-yamcs/blob/master/webpack.config.js#L60) and never relied on app.js. No external projects should be relying on app.js

**Comment by scottbell** [comment]
If we want to have it match the architecture of the main openmct project, I guess we'll have `webpack-common.js`, a `webpack-dev.js`, and a `wepack-prod.js`. We'll manage which we use based on `npm` scripts rather than environment variables. And the `webpack-dev-server` will only be available for development purposes.

**Comment by scottbell** [comment]
@akhenry one other question - it seems like `webpack-dev-server` (i.e., `npm start`) should always want `build:example`. Is that correct?

**Comment by scottbell** [comment]
To test:
- Run through normal ["Running the Example" instructions](https://github.com/akhenry/openmct-yamcs/blob/master/README.md) and ensure development setup works.
- Run `npm run build:dist` to ensure production build works.

**Comment by ozyx** [comment]
Verified-- Testathon 11/14/22
