### ISSUE TITLE
Object Provider should provide search capability

### ISSUE THREAD

**Issue by davetsay** [akhenry/openmct-yamcs#31]
## Overview
Should provide backend search capability

## Steps to Reproduce
1. search for yamcs parameters
2. search for yamcs systems
3. search for yamcs subsystems

**Comment by unlikelyzero** [comment]
@akhenry  to test. This was possibly missed in a previous testathon

**Comment by akhenry** [comment]
Verified fixed. 

Note: It's returning everything that I search for, but I also get additional results. This appears to be because the parameter search capability in Yaamcs [searches on name __and__ on Yamcs namespace](https://docs.yamcs.org/yamcs-http-api/mdb/list-parameters/). This is not necessarily a bad thing. eg. if I search for a subsystem, it's also returning the member parameters of that subsystem. This is often useful, however it's not necessarily obvious to the user what's happening.
